### ISSUE TITLE
Trying to connect to my node but getting this error.

### ISSUE THREAD

**Issue by xippix1** [michielpost/NanoRPC#3]
I made a nano node on a server and I'm trying to connect to it. The node is still syncing to the blockchain, but it seems like this error has nothing to do with that. 

> Exception thrown: 'Newtonsoft.Json.JsonReaderException' in mscorlib.dll
> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
>    at Newtonsoft.Json.JsonTextReader.ParseValue()
>    at Newtonsoft.Json.JsonTextReader.Read()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at RestEase.JsonResponseDeserializer.Deserialize[T](String content, HttpResponseMessage response, ResponseDeserializerInfo info)
>    at RestEase.Implementation.Requester.Deserialize[T](String content, HttpResponseMessage response, IRequestInfo requestInfo)
>    at RestEase.Implementation.Requester.<RequestAsync>d__41`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at CryptoMonitor.Nano.TestNano.<Test>d__0.MoveNext() in C:\Users\benla\source\repos\CryptoMonitor\CryptoMonitor\Nano\TestNano.cs:line 22

Here's the code

```
        internal static async void Test()
        {
            var client = NanoClient.GetClient(@"http://IP:PORT/");

            AccountBalanceResponse accountResult = new AccountBalanceResponse();

            try
            {
                accountResult = await client.AccountBalance(new AccountBalanceRequest
                {
                    Account = "NANO_ADDRESS"
                });
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }

            Console.WriteLine("Current Balance = " + accountResult.Balance);
        }
```

**Comment by michielpost** [comment]
Maybe there have been API changes. But a `<`? Looks like the node returns html instead of json.
I don't have any time this week to look into this. Probably next week.

Maybe you can debug it using Fiddler and see what the Nano rpc returns.

**Comment by michielpost** [comment]
I did a test and the AccountBalanceRequest works fine. 
Are you connected to your own node? `http://localhost:7076`
Did you enable RPC in the config.json?

**Comment by xippix1** [comment]
I was actually trying to connect remotely to the node. Does that not work?

**Comment by xippix1** [comment]
I was trying to connect through port 80, and that gave me the json error. I checked with fiddler and it does indeed just load the webpage. When i tried to connect through port 7076 it just gives me a time-out.

**Comment by michielpost** [comment]
You might need to open port 7076 (on your router?) so you can connect to the machine. But it's probably not a good idea to expose this port to the internet.

**Comment by xippix1** [comment]
Sorry, I completely misunderstood the use-case for this. I thought I could run a remote node and communicate with it from my local machine. It took some time and research but I figured out how to use this correctly with a node. Thanks for the help!
